@startuml er
entity "product" as product {
  + id : int <<PK>>
  name : varchar(200)
  price : int
  image : varchar(200)
}

entity "login" as login {
  + id : int <<PK>>
  nickname : varchar(10) <<unique>>
  password : varchar(100)
}

entity "password_reset" as password_reset {
  + id : int <<PK>>
  login_id : int <<FK>>
  token : varchar(100)
}

product ||--o{ favorite
login ||--o{ password_reset
@enduml
