@startuml er
entity "products" as products {
  +id [PK]
  stock
  created_at
  updated_at
  name
  category
  main_image
  sub_image1
  sub_image2
  sub_image3
  sub_image4
  variety
  price
  size
  description
  cultivation_guide
  tags
}

entity "user_master" as user_master {
  +id [PK]
  nickname
  password
  created_at
  updated_at
}

entity "password_reset" as password_reset {
  +id [PK]
  user_id [FK]
  token
  created_at
}

entity "favorite_master" as favorite_master {
  customer_id [FK]
  product_id [FK]
  created_at
}

entity "news" as news {
  +id [PK]
  date
  content
}

products ||-o{ favorite_master
user_master ||-o{ favorite_master
user_master ||-o{ password_reset

@enduml
