graph LR

A[ユーザー] -- 商品を閲覧 --> B[商品一覧表示]
B -- 商品を選択 --> C[商品詳細表示]
C -- カートに追加 --> D[カート内容確認]
D -- 注文手続き開始 --> E[ログインチェック]
E -- ログイン済み --> F[配送先選択]
F -- 配送先選択済み --> G[支払い方法選択]
G -- 支払い方法選択済み --> H[注文内容確認]
H -- 注文内容確認済み --> I[注文確定]
I -- 注文確定済み --> J[注文完了]
E -- 未ログイン --> K[新規会員登録]
K -- 会員登録完了 --> F
E -- 未ログイン&ゲスト注文 --> G
G -- ゲスト注文確定 --> H
H -- 注文内容確認済み --> I
I -- 注文確定済み --> J
